// Copyright 2024 Santosh Kumar (@santosh)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define OLED_TIMEOUT 5000
#define OLED_BRIGHTNESS 120
#define SPLIT_OLED_ENABLE

#define SPLIT_LAYER_STATE_ENABLE

#define TRI_LAYER_LOWER_LAYER 2
#define TRI_LAYER_UPPER_LAYER 3
#define TRI_LAYER_ADJUST_LAYER 4

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 120

#define LSPO_KEYS KC_LSFT, KC_LSFT, KC_8
#define RSPC_KEYS KC_RSFT, KC_RSFT, KC_9

#define LCPO_KEYS KC_LCTL, KC_RALT, KC_QUOT
#define RCPC_KEYS KC_RCTL, KC_RALT, KC_NUHS

#define LAPO_KEYS KC_LALT, KC_RALT, KC_LBRC
#define RAPC_KEYS KC_RALT, KC_RALT, KC_RBRC